-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.car
(
    car_id integer NOT NULL,
    brand character varying(50) NOT NULL,
    model character varying(50) NOT NULL,
    "VIN_number" character varying(50) NOT NULL,
    year_of_manufacture timestamp(4) without time zone NOT NULL,
    plate_number character varying(50) NOT NULL,
    CONSTRAINT car_id PRIMARY KEY (car_id)
);

CREATE TABLE IF NOT EXISTS public.registration
(
    registration_id integer NOT NULL,
    car_id integer NOT NULL,
    owner_id integer NOT NULL,
    registration_date timestamp(4) without time zone NOT NULL,
    registration_authority integer NOT NULL,
    PRIMARY KEY (registration_id)
);

CREATE TABLE IF NOT EXISTS public.owner
(
    owner_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(50) NOT NULL,
    PRIMARY KEY (owner_id)
);

CREATE TABLE IF NOT EXISTS public."TechnicalCondition"
(
    "TechnicalCondition_id" integer NOT NULL,
    car_id integer NOT NULL,
    mileage integer NOT NULL,
    inspection_date timestamp(4) without time zone NOT NULL,
    inspection_results integer NOT NULL,
    PRIMARY KEY ("TechnicalCondition_id")
);

CREATE TABLE IF NOT EXISTS public.insurance
(
    insurance_id integer NOT NULL,
    car_id integer NOT NULL,
    insurance_company character varying(50) NOT NULL,
    "policy_number " integer NOT NULL,
    "start_date " timestamp without time zone NOT NULL,
    "end_date " timestamp without time zone NOT NULL,
    PRIMARY KEY (insurance_id)
);

ALTER TABLE IF EXISTS public.registration
    ADD FOREIGN KEY (car_id)
    REFERENCES public.car (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.registration
    ADD FOREIGN KEY (owner_id)
    REFERENCES public.owner (owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TechnicalCondition"
    ADD FOREIGN KEY (car_id)
    REFERENCES public.car (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.insurance
    ADD FOREIGN KEY (car_id)
    REFERENCES public.car (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;